version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.10
    working_directory: ~/project

    steps:
      - checkout

      - restore_cache:
          keys:
            - poetry-cache-{{ checksum "poetry.lock" }}
            - poetry-cache-

      - run:
          name: Install Poetry
          command: |
            curl -sSL https://install.python-poetry.org | python3 -
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Install dependencies
          command: |
            source $BASH_ENV
            poetry config virtualenvs.create false
            poetry install --no-interaction

      - save_cache:
          paths:
            - ~/.cache/pypoetry
            - ~/.cache/pip
            - ~/.cache/virtualenvs
          key: poetry-cache-{{ checksum "poetry.lock" }}

      - run:
          name: Run pre-commit hooks
          command: |
            source $BASH_ENV
            poetry run pre-commit run --all-files

      - run:
          name: Run tests
          command: |
            source $BASH_ENV
            poetry run pytest tests/

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
